name: nix

inputs:
  workdir:
    required: true

runs:
  using: "composite"
  steps:
  - name: Install Deps
    uses: cachix/install-nix-action@v15
    with:
      nix_path: nixpkgs=channel:nixos-22.11
  - name: Set Up Build Cache
    uses: actions/cache@v2
    with:
      path: |
        /nix
      key: nix-${{ inputs.workdir }}-${{ hashFiles(format('{0}/shell.nix', inputs.workdir)) }}
  - name: Run
    shell: bash
    working-directory: ${{ inputs.workdir }}
    run: nix-shell --pure --run './run.sh --help'
