name: C

on:
  push:
    paths:
    - 'c/**'
    - '.github/workflows/c.yml'
    - '.github/workflows/common.yml'
    - 'flake.*'
  pull_request:
    paths:
    - 'c/**'
    - '.github/workflows/c.yml'
    - '.github/workflows/common.yml'
    - 'flake.*'
  workflow_dispatch:

jobs:
  common:
    name: Common
    uses: ./.github/workflows/common.yml
    with:
      workdir: c
      format-pkgs: clang-format-14
      build-pkgs: gcc cmake libsdl2-dev
      cache-paths: |
        c/build
      cache-key: build
