name: Devkit

on:
  workflow_call:
    inputs:
      lang:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Publish
      uses: elgohr/Publish-Docker-Github-Action@main
      with:
        name: shish2k/rosettaboy-devkit-${{ inputs.lang }}
        dockerfile: .docker/${{ inputs.lang }}.dockerfile
        buildoptions: "--build-arg VERSION=${{ inputs.version }}"
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: ${{ inputs.version }}
        platforms: linux/amd64,linux/arm64
