name: Devkit (python)

on:
  push:
    branches:
    - master
    - main
    paths:
    - '.docker/python.dockerfile'
    - '.github/workflows/devkit-python.yml'
  pull_request:
    paths:
    - '.docker/python.dockerfile'
    - '.github/workflows/devkit-python.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        lang: ["python"]
        version: ["3.11.5"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Publish
      uses: elgohr/Publish-Docker-Github-Action@main
      with:
        name: shish2k/rosettaboy-devkit-${{ matrix.lang }}
        dockerfile: .docker/${{ matrix.lang }}.dockerfile
        buildoptions: "--build-arg VERSION=${{ matrix.version }}"
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: ${{ matrix.version }}
        platforms: linux/amd64,linux/arm64
