name: PHP

on:
  push:
    branches:
    - master
    paths:
    - 'php/**'
    - '.github/workflows/php.yml'
  pull_request:
    paths:
    - 'php/**'
    - '.github/workflows/php.yml'
  workflow_dispatch:

jobs:
  common:
    name: Common
    uses: ./.github/workflows/common.yml
    with:
      workdir: php
      format-deps: |
        sudo apt-get update && sudo apt-get install -y php-cli
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php
        php -r "unlink('composer-setup.php');"
        ./composer.phar require friendsofphp/php-cs-fixer
      build-deps: sudo apt-get update && sudo apt-get install -y php-cli
