name: PHP

on:
  push:
    paths:
    - 'php/**'
    - '.github/workflows/php.yml'
    - '.github/workflows/common.yml'
  pull_request:
    paths:
    - 'php/**'
    - '.github/workflows/php.yml'
    - '.github/workflows/common.yml'
  workflow_dispatch:

jobs:
  common:
    name: Common
    uses: ./.github/workflows/common.yml
    with:
      workdir: php
      format-pkgs: php-cli
      build-pkgs: php-cli
