name: Python

on:
  push:
    branches:
    - master
    paths:
    - 'py/**'
    - '.github/workflows/py.yml'
  pull_request:
    paths:
    - 'py/**'
    - '.github/workflows/py.yml'
  workflow_dispatch:

jobs:
  format:
    name: Format
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Format
      uses: "./.github/templates/format"
      with:
        workdir: py
        deps: sudo apt-get update && sudo apt-get install -y python3.11-venv
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      uses: "./.github/templates/build"
      with:
        workdir: py
        deps: sudo apt-get update && sudo apt-get install -y python3.11-venv
        cache-paths: |
          py/venv
        cache-key: venv
