name: Python

on:
  push:
    paths:
    - 'py/**'
    - '.github/workflows/py.yml'
    - '.github/workflows/common.yml'
    - 'flake.*'
  pull_request:
    paths:
    - 'py/**'
    - '.github/workflows/py.yml'
    - '.github/workflows/common.yml'
    - 'flake.*'
  workflow_dispatch:

jobs:
  common:
    name: Common
    uses: ./.github/workflows/common.yml
    with:
      workdir: py
      format-pkgs: python3.11-venv
      build-pkgs: python3.11-venv
      cache-paths: |
        py/venv
        ~/.cache/pip
      cache-key: venv
