name: Zig

on:
  push:
    branches:
    - master
    paths:
    - 'zig/**'
    - '.github/workflows/zig.yml'
  pull_request:
    paths:
    - 'zig/**'
    - '.github/workflows/zig.yml'
  workflow_dispatch:

jobs:
  format:
    name: Format
    runs-on: ubuntu-22.04
    steps:
    - name: Set Up Toolchain
      uses: goto-bus-stop/setup-zig@v1
      with:
        version: master
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check
      working-directory: zig
      run: ./format.sh && git diff --exit-code
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
    - name: Install Deps
      run: sudo apt-get update && sudo apt-get install -y libsdl2-dev
    - name: Set Up Toolchain
      uses: goto-bus-stop/setup-zig@v1
      with:
        version: master
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build
      run: ./zig/run.sh --help
    - name: CPU Integration Tests
      run: ./utils/blargg.py zig
    - name: Benchmark
      run: ./utils/bench.py zig --default --frames 10
