name: Zig

on:
  push:
    branches:
    - master
    paths:
    - 'zig/**'
    - '.github/workflows/zig.yml'
  pull_request:
    paths:
    - 'zig/**'
    - '.github/workflows/zig.yml'
  workflow_dispatch:

jobs:
  common:
    name: Common
    uses: ./.github/workflows/common.yml
    with:
      workdir: zig
      with-zig: true
      build-pkgs: libsdl2-dev
