name: Zig

on:
  push:
    paths:
    - 'zig/**'
    - '.github/workflows/zig.yml'
    - '.github/workflows/common.yml'
    - 'flake.*'
  pull_request:
    paths:
    - 'zig/**'
    - '.github/workflows/zig.yml'
    - '.github/workflows/common.yml'
    - 'flake.*'
  workflow_dispatch:

jobs:
  common:
    name: Common
    uses: ./.github/workflows/common.yml
    with:
      workdir: zig
      with-zig: 0.11.0-dev.3704+729a051e9
      build-pkgs: libsdl2-dev
